version: "3"
services:
  bootloader:
    build: .
    command: /bin/sh -c 'cd /app/bootloader && cargo build -Z unstable-options --out-dir /dist'
    volumes:
      - ./dist/:/dist
      - ./:/app
  kernel:
    build: .
    command: /bin/sh -c 'cd /app/kernel && cargo build -Z unstable-options --out-dir /dist'
    volumes:
      - ./dist/:/dist
      - ./:/app